// ═══════════════════════════════════════════════════════════════════════════
// /u/[token]  —  Sprint 14C.1 nurture unsubscribe handler
//
// Receives signed opt-out tokens generated by /api/nurture-send.
// Token format: base64url(client_id + '.' + hex_hmac_sha256(secret, client_id))
//
// On valid token:
//   - clients.nurture_opted_out_at = now()
//   - GET → renders a friendly confirmation page
//   - POST → 204 No Content (RFC 8058 one-click List-Unsubscribe-Post)
//
// On invalid token → 400 with a generic error page (don't leak details).
// On already-opted-out → still returns success (idempotent — Gmail's
// one-click hits the URL repeatedly and we want it to stay friendly).
//
// CF Pages dynamic-route file: bpb 3/functions/u/[token].js
// ═══════════════════════════════════════════════════════════════════════════

export async function onRequestGet(ctx)  { return handle(ctx, 'GET'); }
export async function onRequestPost(ctx) { return handle(ctx, 'POST'); }

async function handle({ request, env, params }, method) {
  const token = params && params.token ? String(params.token) : '';
  if (!token) {
    return method === 'POST'
      ? new Response(null, { status: 400 })
      : htmlResponse(400, errorPage('Missing unsubscribe token.'));
  }

  if (!env.SUPABASE_URL || !env.SUPABASE_SERVICE_ROLE_KEY) {
    return method === 'POST'
      ? new Response(null, { status: 500 })
      : htmlResponse(500, errorPage('Server misconfigured. Reply to the email and we\'ll remove you manually.'));
  }

  const sb = (path, init) =>
    fetch(env.SUPABASE_URL + '/rest/v1/' + path, {
      ...init,
      headers: {
        apikey: env.SUPABASE_SERVICE_ROLE_KEY,
        Authorization: 'Bearer ' + env.SUPABASE_SERVICE_ROLE_KEY,
        ...((init && init.headers) || {}),
      },
    });

  // Load nurture_config to get the HMAC secret + business name for confirmation page
  const cfgResp = await sb('nurture_config?id=eq.1&select=unsub_secret,business_name&limit=1');
  if (!cfgResp.ok) {
    return method === 'POST'
      ? new Response(null, { status: 500 })
      : htmlResponse(500, errorPage('Could not load configuration.'));
  }
  const cfgRows = await cfgResp.json();
  if (!cfgRows || cfgRows.length === 0) {
    return method === 'POST'
      ? new Response(null, { status: 500 })
      : htmlResponse(500, errorPage('Configuration missing.'));
  }
  const { unsub_secret: secret, business_name: businessName } = cfgRows[0];

  // ─── Decode + verify token ──────────────────────────────────────────
  let decoded;
  try {
    decoded = base64UrlDecode(token);
  } catch {
    return method === 'POST'
      ? new Response(null, { status: 400 })
      : htmlResponse(400, errorPage('Invalid unsubscribe link.'));
  }

  const dotIdx = decoded.indexOf('.');
  if (dotIdx <= 0 || dotIdx >= decoded.length - 1) {
    return method === 'POST'
      ? new Response(null, { status: 400 })
      : htmlResponse(400, errorPage('Invalid unsubscribe link.'));
  }
  const clientId = decoded.slice(0, dotIdx);
  const providedSig = decoded.slice(dotIdx + 1);

  // Validate clientId looks like a UUID before round-tripping to DB
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(clientId)) {
    return method === 'POST'
      ? new Response(null, { status: 400 })
      : htmlResponse(400, errorPage('Invalid unsubscribe link.'));
  }

  const expectedSig = await hmacSha256Hex(secret, clientId);
  if (!timingSafeEqual(providedSig, expectedSig)) {
    return method === 'POST'
      ? new Response(null, { status: 400 })
      : htmlResponse(400, errorPage('This unsubscribe link is no longer valid. Reply to the email and we\'ll remove you manually.'));
  }

  // ─── Mark client opted out (idempotent) ─────────────────────────────
  const updResp = await sb('clients?id=eq.' + encodeURIComponent(clientId), {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', Prefer: 'return=minimal' },
    body: JSON.stringify({
      nurture_opted_out_at: new Date().toISOString(),
    }),
  });

  // We tolerate failures here on purpose for the POST path — Gmail will keep
  // hitting the URL even after success. As long as the HMAC verified, treat
  // it as a successful unsubscribe from the user's perspective.
  if (!updResp.ok && method === 'GET') {
    return htmlResponse(500, errorPage('We couldn\'t complete your unsubscribe. Reply to the email and we\'ll remove you manually.'));
  }

  // ─── Respond ────────────────────────────────────────────────────────
  if (method === 'POST') {
    return new Response(null, { status: 204 });
  }
  return htmlResponse(200, confirmationPage(businessName || 'Paver Portal'));
}

// ─── HTML pages ──────────────────────────────────────────────────────
function confirmationPage(businessName) {
  const safeName = escapeHtml(businessName);
  return '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">' +
    '<meta name="viewport" content="width=device-width, initial-scale=1">' +
    '<title>Unsubscribed · ' + safeName + '</title>' +
    '<style>' +
    'body{margin:0;padding:0;background:#faf8f3;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;color:#353535;}' +
    '.wrap{max-width:520px;margin:80px auto;padding:0 20px;text-align:center;}' +
    '.card{background:#fff;border-radius:14px;padding:40px 32px;box-shadow:0 4px 24px rgba(0,0,0,0.06);}' +
    '.eyebrow{font-family:SF Mono,Menlo,monospace;font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:#9c7440;margin-bottom:8px;font-weight:600;}' +
    'h1{margin:0 0 14px;font-size:22px;font-weight:600;letter-spacing:-0.012em;color:#33281c;}' +
    'p{margin:0 0 12px;font-size:14px;line-height:1.6;color:#666;}' +
    '.checkmark{width:54px;height:54px;border-radius:50%;background:#f1e7d3;color:#9c7440;display:inline-flex;align-items:center;justify-content:center;margin:0 auto 18px;font-size:26px;}' +
    '.foot{margin-top:18px;font-size:11px;color:#888;}' +
    '</style></head><body><div class="wrap"><div class="card">' +
    '<div class="checkmark">✓</div>' +
    '<div class="eyebrow">Unsubscribed</div>' +
    '<h1>You\'re all set.</h1>' +
    '<p>You won\'t receive any more nurture emails from ' + safeName + '. Existing project communication from your designer will continue normally.</p>' +
    '<p>If this was a mistake, just reply to any email we sent and we\'ll add you back.</p>' +
    '</div><div class="foot">' + safeName + '</div></div></body></html>';
}

function errorPage(message) {
  return '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">' +
    '<meta name="viewport" content="width=device-width, initial-scale=1">' +
    '<title>Unsubscribe</title>' +
    '<style>' +
    'body{margin:0;padding:0;background:#faf8f3;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;color:#353535;}' +
    '.wrap{max-width:520px;margin:80px auto;padding:0 20px;text-align:center;}' +
    '.card{background:#fff;border-radius:14px;padding:40px 32px;box-shadow:0 4px 24px rgba(0,0,0,0.06);}' +
    'h1{margin:0 0 14px;font-size:20px;font-weight:600;color:#b04040;}' +
    'p{margin:0 0 12px;font-size:14px;line-height:1.6;color:#666;}' +
    '</style></head><body><div class="wrap"><div class="card">' +
    '<h1>Couldn\'t process unsubscribe</h1>' +
    '<p>' + escapeHtml(message) + '</p>' +
    '</div></div></body></html>';
}

function htmlResponse(status, html) {
  return new Response(html, {
    status,
    headers: { 'Content-Type': 'text/html; charset=utf-8' },
  });
}

// ─── Helpers ─────────────────────────────────────────────────────────
function base64UrlDecode(s) {
  const std = s.replace(/-/g, '+').replace(/_/g, '/');
  const padded = std + '='.repeat((4 - std.length % 4) % 4);
  return atob(padded);
}

async function hmacSha256Hex(secret, message) {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    'raw',
    enc.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, enc.encode(message));
  return Array.from(new Uint8Array(sig))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');
}

// Constant-time string comparison — avoids timing oracles on signature check.
function timingSafeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return diff === 0;
}

function escapeHtml(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}
