// ═══════════════════════════════════════════════════════════════════════════
// Cloudflare Pages Function — POST /api/parse-bid-pdf
//
// Accepts a multipart form upload with field "pdf". Forwards the PDF to the
// Anthropic API with a structured extraction prompt calibrated to the
// JobNimbus bid format used by Paver Portal. Returns structured JSON.
//
// Requires env variable: ANTHROPIC_API_KEY (set as encrypted secret in CF
// Pages dashboard → Settings → Environment variables).
// ═══════════════════════════════════════════════════════════════════════════

const MODEL = 'claude-sonnet-4-6';
const MAX_PDF_MB = 30;

const EXTRACTION_PROMPT = `You are parsing a Paver Portal bid PDF generated by JobNimbus. Extract structured data as JSON.

CLIENT INFO (cover page, usually page 1):
- client_name: Primary client name, usually in large type on the right side of the cover (e.g., "Sahil Handa")
- client_email: Email address, usually below client name
- client_phone: Phone number, usually below email, formatted like "(217) 419-9639"
- project_address: Street address only (e.g., "1728 Whitham Ave")
- project_city: City only (e.g., "Los Altos")
- project_state: 2-letter state code (e.g., "CA")
- project_zip: ZIP code (e.g., "94024")
- project_label: The left-side header text on the cover page, often the client's first names as a project nickname (e.g., "SAHIL & RITIKA"). Uppercase is fine to preserve.
- proposal_date: ISO YYYY-MM-DD parsed from cover page date like "APR 10, 2026"

ESTIMATE SECTIONS (usually starting around page 9, under "ESTIMATE" header):
Each section follows this pattern:
  Description
  <Section Name>
  <line item 1 description>
  <line item 2 description>
  ...
  Section Total $X,XXX.XX

Section names look like: "Demolition Front & Back", "Backyard | Grass & Irrigation", "Backyard | Hardscape", "Backyard | Trees", "Front Yard | Hardscape", "Front Yard | Grass, Plants & Irrigation", "Discounts".

For each section extract:
- name: Section name exactly as written, preserving pipes and capitalization
- total_amount: Numeric value of "Section Total" line. Negative for discount sections.
- line_items: Array of strings describing the scope. Preserve the order. Each item should be one logical scope (e.g., one paragraph or bullet). Keep them concise but complete — don't truncate mid-sentence.

IMPORTANT: Skip the "Installation Process" preamble at the top of the ESTIMATE page. That's boilerplate about general paver installation methodology and is NOT a section with a total. Sections always end with "Section Total".

BID TOTALS (end of estimate pages):
- subtotal: Value labeled "Estimate subtotal"
- discount_amount: Value labeled "Credit" (negative; the parenthesized format like "($3,685.77)" means -3685.77)
- final_total: Value labeled "Total" at the very bottom (after all credits applied)

MATERIALS MENTIONED (scan the entire bid, including Project Overview, scope sections, and any spec sheets):
Look for named products like Belgard Catalina Grana, Belgard Dimensions Slab, Belgard Belair, Belgard Steeple Crest, Trex Transcend Lineage, etc. For each unique product extract:
- manufacturer: e.g., "Belgard", "Trex"
- product_name: e.g., "Catalina Grana", "Dimensions Slab", "Transcend Lineage", "Belair"
- color: Color name if specified, e.g., "Scandina Grey", "Biscayne", "Victorian"
- size_spec: Size spec if specified, e.g., "24x24", "6x9", "60mm"
- application: Brief note on where it's used, e.g., "central paver patio", "running border edger", "retaining wall", "staircase step boards"

Return ONLY valid JSON. No markdown code fences, no prose commentary, no explanation.

SCHEMA:
{
  "client": {
    "client_name": string|null,
    "client_email": string|null,
    "client_phone": string|null,
    "project_address": string|null,
    "project_city": string|null,
    "project_state": string|null,
    "project_zip": string|null,
    "project_label": string|null,
    "proposal_date": string|null
  },
  "sections": [
    { "name": string, "total_amount": number, "line_items": string[] }
  ],
  "totals": {
    "subtotal": number|null,
    "discount_amount": number|null,
    "final_total": number|null
  },
  "materials_mentioned": [
    {
      "manufacturer": string|null,
      "product_name": string|null,
      "color": string|null,
      "size_spec": string|null,
      "application": string|null
    }
  ]
}`;

// ───────────────────────────────────────────────────────────────────────────
// Utilities
// ───────────────────────────────────────────────────────────────────────────
function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  let binary = '';
  const chunkSize = 8192;
  for (let i = 0; i < bytes.byteLength; i += chunkSize) {
    const chunk = bytes.subarray(i, Math.min(i + chunkSize, bytes.byteLength));
    binary += String.fromCharCode.apply(null, chunk);
  }
  return btoa(binary);
}

function jsonResponse(payload, status = 200) {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { 'content-type': 'application/json; charset=utf-8' }
  });
}

// ───────────────────────────────────────────────────────────────────────────
// Main handler
// ───────────────────────────────────────────────────────────────────────────
export async function onRequestPost(context) {
  const { request, env } = context;

  if (!env.ANTHROPIC_API_KEY) {
    return jsonResponse({
      error: 'ANTHROPIC_API_KEY environment variable not configured on this Cloudflare Pages deployment. Add it in Settings → Environment variables (encrypted).'
    }, 500);
  }

  // Parse form data
  let pdfFile;
  try {
    const formData = await request.formData();
    pdfFile = formData.get('pdf');
  } catch (err) {
    return jsonResponse({ error: 'Invalid form data', details: err.message }, 400);
  }

  if (!pdfFile || typeof pdfFile === 'string' || !pdfFile.arrayBuffer) {
    return jsonResponse({ error: 'No PDF file in "pdf" form field' }, 400);
  }

  // Size check
  const buffer = await pdfFile.arrayBuffer();
  const sizeMB = buffer.byteLength / (1024 * 1024);
  if (sizeMB > MAX_PDF_MB) {
    return jsonResponse({
      error: `PDF too large (${sizeMB.toFixed(1)} MB). Max is ${MAX_PDF_MB} MB.`
    }, 400);
  }

  // Base64 encode
  const base64 = arrayBufferToBase64(buffer);

  // Call Anthropic API
  let apiResponse;
  try {
    apiResponse = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'x-api-key': env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json'
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 8000,
        messages: [
          {
            role: 'user',
            content: [
              {
                type: 'document',
                source: {
                  type: 'base64',
                  media_type: 'application/pdf',
                  data: base64
                }
              },
              {
                type: 'text',
                text: EXTRACTION_PROMPT
              }
            ]
          }
        ]
      })
    });
  } catch (err) {
    return jsonResponse({
      error: 'Network error calling Anthropic API',
      details: err.message
    }, 502);
  }

  const apiData = await apiResponse.json().catch(() => null);

  if (!apiResponse.ok) {
    return jsonResponse({
      error: `Anthropic API returned ${apiResponse.status}`,
      details: apiData
    }, 502);
  }

  // Extract text content
  const textBlock = apiData?.content?.find?.(c => c.type === 'text');
  const textContent = textBlock?.text;
  if (!textContent) {
    return jsonResponse({
      error: 'Claude returned no text content',
      raw_response: apiData
    }, 500);
  }

  // Parse as JSON (strip any accidental markdown fences)
  const cleaned = textContent
    .replace(/^```json\s*/i, '')
    .replace(/^```\s*/i, '')
    .replace(/\s*```\s*$/, '')
    .trim();

  let parsed;
  try {
    parsed = JSON.parse(cleaned);
  } catch (err) {
    return jsonResponse({
      error: 'Claude returned text that is not valid JSON',
      raw_response: textContent,
      parse_error: err.message
    }, 500);
  }

  return jsonResponse({
    success: true,
    parsed,
    meta: {
      model: apiData.model,
      usage: apiData.usage,
      pdf_size_mb: parseFloat(sizeMB.toFixed(2))
    }
  });
}

// Handle preflight (just in case)
export async function onRequestOptions() {
  return new Response(null, {
    status: 204,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-allow-methods': 'POST, OPTIONS',
      'access-control-allow-headers': 'content-type'
    }
  });
}
